# Import

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/filtered_marathons_results.csv")
print(df.isna().sum())
print(df.shape)
print(df.columns)

Bib                  0
Name                 0
Age                  0
M/F                  0
City                 1
State             8902
Country              0
Citizen          75626
Parathletics         0
5K                   0
10K                  0
15K                  0
20K                  0
Half                 0
25K                  0
30K                  0
35K                  0
40K                  0
Pace                 0
Proj Time        52661
Official Time        0
Overall              0
Gender               0
Division             0
Year                 0
dtype: int64
(79038, 25)
Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall', 'Gender',
       'Division', 'Year'],
      dtype='str')

C:\Users\Liliu\AppData\Local\Temp\ipykernel_22976\3262035383.py:1: DtypeWarning: Columns (0: Bib, 1: Proj Time) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/filtered_marathons_results.csv")

In [3]:
all_repeats = df[df.duplicated(subset=['Name','M/F', 'City'], keep=False)].sort_values(['Name', 'City'])
print(all_repeats.shape)


#all_repeats.to_csv("data/repeated_names.csv", index=False)

(19162, 25)

In [85]:
counts = df.groupby(['Name', 'M/F', 'City'])['Name'].transform('size')
more_than_3 = df[counts == 3].sort_values(['Name', 'M/F', 'City'])

print(f"Found {more_than_3['Name'].nunique()} names repeated more than 2 times.")
df_temp = all_repeats.groupby(['Name', 'M/F', 'City']).size().reset_index(name='Count')
print(df_temp.head())
df_temp.to_csv("data/name_counts.csv", index=False)

Found 1896 names repeated more than 2 times.
                     Name M/F       City  Count
0       Abanses, Jolene C   F       Lutz      3
1            Abber, Tracy   F     Dedham      3
2  Abbondanza, Stephen R.   M    Everett      2
3        Abbott, Patricia   F       Katy      2
4           Abbott, Wendy   F  Rochester      3

In [58]:
df_country_city = df.groupby(['City', 'Country']).size().reset_index(name='Count').sort_values('City', ascending=False)
print(df_country_city.head())

duplicates = df_country_city.groupby('City').filter(lambda x: len(x) > 1)
print(duplicates.head(20))
print(f"Found {duplicates['City'].nunique()} cities with multiple countries.")

             City Country  Count
10154        Älta     SWE      1
10153      upland     USA      1
10152  providence     USA      1
10151      ottawa     CAN      1
10150     hingham     USA      1
                              City Country  Count
10125  Zhubei City, Hsinchu County     TWN      2
10124  Zhubei City, Hsinchu County     TPE      1
10099                       Zamora     ESP      1
10100                       Zamora     MEX      1
10068                         York     GBR      6
10069                         York     USA     69
10067                         York     CAN      1
10043                     Yarmouth     CAN      4
10044                     Yarmouth     USA     16
10023                      Wyoming     USA     11
10022                      Wyoming     CAN      2
9991                     Worcester     USA     88
9990                     Worcester     GBR      4
9977                     Woodstock     USA     19
9976                     Woodstock     CAN      2
9956                    Woodbridge     USA     28
9955                    Woodbridge     GBR      1
9954                    Woodbridge     CAN      4
9900                      Winfield     CAN      1
9901                      Winfield     USA     11
Found 332 cities with multiple countries.

# 2014

In [3]:
df2014 = pd.read_csv("data/Boston_2014-2019/results2014.csv")
print(df2014.isna().sum())
print(df2014.shape)
print(df2014.columns)
df2014.rename(columns={'age': 'Age', 'official_time': 'Official Time', 'gender': 'M/F', 'pace': 'Pace', 'overall': 'overall_result'}, inplace=True)
df2014['Year'] = 2014

display_name           0
age                    0
gender                 0
residence              0
pace                   0
official_time          0
overall                0
gender_result          0
division_result        0
seconds                0
first_name             0
last_name          15943
dtype: int64
(31809, 12)
Index(['display_name', 'age', 'gender', 'residence', 'pace', 'official_time',
       'overall', 'gender_result', 'division_result', 'seconds', 'first_name',
       'last_name'],
      dtype='str')

In [4]:

def split_residence(row):
    parts = [p.strip() for p in row.split(',')]
    
    if len(parts) == 3:
        return parts[0], parts[2] # City, Country
    elif len(parts) == 2:
        return parts[0], parts[1] # City, Country
    else:
        return parts[0], None      # City, Missing Country

# Apply the split
df2014[['City', 'Country']] = df2014['residence'].apply(lambda x: pd.Series(split_residence(x)))
df2014['City'] = df2014['City'].str.strip()
df2014['Country'] = df2014['Country'].str.strip()
print(df2014.isna().sum())

df2014.head()

display_name           0
Age                    0
M/F                    0
residence              0
Pace                   0
Official Time          0
overall_result         0
gender_result          0
division_result        0
seconds                0
first_name             0
last_name          15943
Year                   0
City                   0
Country             6807
dtype: int64

,display_name,Age,M/F,residence,Pace,Official Time,overall_result,gender_result,division_result,seconds,first_name,last_name,Year,City,Country
0,Meb Keflezighi,38,M,"San Diego, CA, USA",00:04:54,2:08:37,1,1,1,7717,Meb,Keflezighi,2014,San Diego,USA
1,Wilson Chebet,28,M,Marakwet,00:04:54,2:08:48,2,2,1,7728,Wilson,Chebet,2014,Marakwet,NaN
2,Frankline Chepkwony,29,M,Koibatek,00:04:54,2:08:50,3,3,2,7730,Frankline,Chepkwony,2014,Koibatek,NaN
3,Vitaliy Shafar,32,M,Lutsk,00:04:56,2:09:37,4,4,1,7777,Vitaliy,Shafar,2014,Lutsk,NaN
4,Markos Geneti,29,M,Addis Ababa,00:04:57,2:09:50,5,5,3,7790,Markos,Geneti,2014,Addis Ababa,NaN

In [53]:
unique_mapping = df_country_city.drop_duplicates('City', keep=False)
mapping_dict = unique_mapping.set_index('City')['Country'].to_dict()

# 2. Get the names of cities that appear with multiple countries
# This uses the 'duplicates' logic you already found
ambiguous_city_names = df_country_city[df_country_city.duplicated('City', keep=False)]['City'].unique()

# Create a mask for rows with missing countries
missing_mask = df2014['Country'].isna()

# 3. Separate rows where the city exists but has multiple possible countries
df_ambiguous = df2014[missing_mask & df2014['City'].isin(ambiguous_city_names)].copy()

# (Optional) Remove these from the main dataframe so you don't process them twice
# df2014 = df2014[~(missing_mask & df2014['City'].isin(ambiguous_city_names))]

# 4. Map the unique countries to the missing values
df2014.loc[missing_mask, 'Country'] = df2014.loc[missing_mask, 'Country'].fillna(df2014['City'].map(mapping_dict))

print(f"Moved {len(df_ambiguous)} ambiguous rows to df_ambiguous.")
print(f"Filled remaining missing countries using unique mappings.")

print(df2014.isna().sum())
print(len(df_ambiguous['City'].unique()), "ambiguous city names:", df_ambiguous['City'].unique())
df_ambiguous.head()

Moved 1186 ambiguous rows to df_ambiguous.
Filled remaining missing countries using unique mappings.
Age                   0
M/F                   0
residence             0
Pace                  0
Official Time         0
overall_result        0
gender_result         0
division_result       0
seconds               0
Year                  0
city                  0
country            6807
City                  0
Country            2407
Name                  0
dtype: int64
201 ambiguous city names: <StringArray>
[     'Moscow',     'Dresden',   'Sao Paulo',       'Miami', 'Northampton',
   'Vancouver',    'Richmond',   'Brentwood',     'Chatham',      'Aurora',
 ...
    'Montague',      'Bolton',   'Salisbury',  'Willoughby',   'Lancaster',
    'Falmouth',   'Rotterdam',    'Abingdon',     'Amherst',       'Milan']
Length: 201, dtype: str

,Age,M/F,residence,Pace,Official Time,overall_result,gender_result,division_result,seconds,Year,city,country,City,Country,Name
28,44,M,Moscow,00:05:22,2:20:43,29,25,2,8443,2014,Moscow,NaN,Moscow,NaN,"Shabunin, Viacheslav V."
90,29,M,Dresden,00:05:42,2:29:41,91,79,36,8981,2014,Dresden,NaN,Dresden,NaN,"Schulze, Marc"
110,32,F,Sao Paulo,00:05:46,2:31:18,111,16,8,9078,2014,Sao Paulo,NaN,Sao Paulo,NaN,"Silva, Adriana Aparecida da"
117,30,M,Miami,00:05:47,2:31:58,118,102,34,9118,2014,Miami,NaN,Miami,NaN,"Martin, Daniel"
142,27,M,Northampton,00:05:51,2:33:29,143,123,52,9209,2014,Northampton,NaN,Northampton,NaN,"Weissinger, Mathew"

In [5]:

df2014['Name'] = df2014['display_name'].str.strip().str.replace(r'^(.*)\s+(\S+)$', r'\2, \1', regex=True)
df2014.drop(columns=['display_name', 'first_name', 'last_name'], inplace=True)
print(df2014.head())

   Age M/F           residence      Pace Official Time  overall_result  \
0   38   M  San Diego, CA, USA  00:04:54       2:08:37               1
1   28   M            Marakwet  00:04:54       2:08:48               2
2   29   M            Koibatek  00:04:54       2:08:50               3
3   32   M               Lutsk  00:04:56       2:09:37               4
4   29   M         Addis Ababa  00:04:57       2:09:50               5

   gender_result  division_result  seconds  Year         City Country  \
0              1                1     7717  2014    San Diego     USA
1              2                1     7728  2014     Marakwet     NaN
2              3                2     7730  2014     Koibatek     NaN
3              4                1     7777  2014        Lutsk     NaN
4              5                3     7790  2014  Addis Ababa     NaN

                   Name
0       Keflezighi, Meb
1        Chebet, Wilson
2  Chepkwony, Frankline
3       Shafar, Vitaliy
4        Geneti, Markos

In [6]:
columns = ['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year']
df2014.columns

Index(['Age', 'M/F', 'residence', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'seconds', 'Year', 'City',
       'Country', 'Name'],
      dtype='str')

# 2018

In [7]:
df2018 = pd.read_csv("data/Boston_2014-2019/results2018.csv")
print(df2018.isna().sum())
print(df2018.shape)
print(df2018.columns)
df2018.rename(columns={'name': 'Name', 'age': 'Age', 'official_time': 'Official Time', 'gender': 'M/F', 'city': 'City', 'pace': 'Pace', 'overall': 'overall_result'}, inplace=True)
df2018['Year'] = 2018

place_overall             0
bib                   25996
name                      0
age                       0
gender                    0
city                      0
state                  4075
country_residence         0
contry_citizenship        0
name_suffix           25996
5k                    25996
10k                   25996
15k                   25996
20k                   25996
half                  25996
25k                   25996
30k                   25996
35k                   25996
40k                   25996
pace                  25996
projected_time        25996
official_time             0
overall                   0
gender_result             0
division_result           0
seconds                   0
first_name              984
last_name              2952
display_name              0
dtype: int64
(25996, 29)
Index(['place_overall', 'bib', 'name', 'age', 'gender', 'city', 'state',
       'country_residence', 'contry_citizenship', 'name_suffix', '5k', '10k',
       '15k', '20k', 'half', '25k', '30k', '35k', '40k', 'pace',
       'projected_time', 'official_time', 'overall', 'gender_result',
       'division_result', 'seconds', 'first_name', 'last_name',
       'display_name'],
      dtype='str')

In [8]:
print(columns)
df2018.columns

['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result', 'gender_result', 'division_result', 'Year']

Index(['place_overall', 'bib', 'Name', 'Age', 'M/F', 'City', 'state',
       'country_residence', 'contry_citizenship', 'name_suffix', '5k', '10k',
       '15k', '20k', 'half', '25k', '30k', '35k', '40k', 'Pace',
       'projected_time', 'Official Time', 'overall_result', 'gender_result',
       'division_result', 'seconds', 'first_name', 'last_name', 'display_name',
       'Year'],
      dtype='str')

# 2019

In [9]:
import linecache

file_path = "data/Boston_2014-2019/results2019.csv"
# Print the exact line causing the error
bad_line = linecache.getline(file_path, 26134)
print(bad_line)

"26144","25629","Munchgesang, Anthony","29","M","New Hartford","CT ","United ","United ",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"5:46:31","26144","14449","5029",20791,NULL,NULL,"Anthony Munchgesang"

In [10]:
df2019 = pd.read_csv("data/Boston_2014-2019/results2019.csv")
print(df2019.isna().sum())
print(df2019.shape)
print(df2019.columns)
df2019.rename(columns={'name': 'Name', 'age': 'Age', 'official_time': 'Official Time', 'gender': 'M/F', 'city': 'City', 'pace': 'Pace', 'overall': 'overall_result'}, inplace=True)
df2019['Year'] = 2019

place_overall             0
bib                       0
name                      0
age                       0
gender                    0
city                      1
state                  5051
country_residence         0
contry_citizenship        0
name_suffix           26646
5k                    26646
10k                   26646
15k                   26646
20k                   26646
half                  26646
25k                   26646
30k                   26646
35k                   26646
40k                   26646
pace                  26646
projected_time        26646
official_time             0
overall                   0
gender_result             0
division_result           0
seconds                   0
first_name            26646
last_name             26646
display_name              0
dtype: int64
(26646, 29)
Index(['place_overall', 'bib', 'name', 'age', 'gender', 'city', 'state',
       'country_residence', 'contry_citizenship', 'name_suffix', '5k', '10k',
       '15k', '20k', 'half', '25k', '30k', '35k', '40k', 'pace',
       'projected_time', 'official_time', 'overall', 'gender_result',
       'division_result', 'seconds', 'first_name', 'last_name',
       'display_name'],
      dtype='str')

In [11]:
missing_city_row = df2019[df2019['City'].isna()]
print(missing_city_row)
df2019 = df2019.dropna(subset=['City'])
print(columns)
df2019.columns

       place_overall   bib           Name  Age M/F City state  \
13457          13464  9074  Bayer, Andrea   38   F  NaN   NaN

      country_residence contry_citizenship  name_suffix  ...  projected_time  \
13457           United             United           NaN  ...             NaN

       Official Time  overall_result  gender_result  division_result  seconds  \
13457        3:46:03           13464           4509             2945    13563

       first_name  last_name  display_name  Year
13457         NaN        NaN  Andrea Bayer  2019

[1 rows x 30 columns]
['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result', 'gender_result', 'division_result', 'Year']

Index(['place_overall', 'bib', 'Name', 'Age', 'M/F', 'City', 'state',
       'country_residence', 'contry_citizenship', 'name_suffix', '5k', '10k',
       '15k', '20k', 'half', '25k', '30k', '35k', '40k', 'Pace',
       'projected_time', 'Official Time', 'overall_result', 'gender_result',
       'division_result', 'seconds', 'first_name', 'last_name', 'display_name',
       'Year'],
      dtype='str')

# Fuse 2014 to 2019 overall

In [12]:
columns = ['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year']
df_overall = df.copy()
df_overall.rename(columns={'Overall': 'overall_result', 'Division': 'division_result', 'Gender': 'gender_result'}, inplace=True)
print(df_overall.columns)
df_overall2 = df_overall[columns]
print(df_overall2.columns)
print(df_overall2.shape)

Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
Index(['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
(79038, 10)

In [13]:
df2014_overall = df2014[columns]
print(df2014_overall.columns)
print(df2014_overall.shape)
df2018_overall = df2018[columns]
print(df2018_overall.columns)
print(df2018_overall.shape)
df2019_overall = df2019[columns]
print(df2019_overall.columns)
print(df2019_overall.shape)

Index(['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
(31809, 10)
Index(['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
(25996, 10)
Index(['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
(26645, 10)

In [14]:
print(79038 + 31809 + 25996 + 26645)
dfall_overall = pd.concat([df2014_overall, df_overall2,df2018_overall, df2019_overall], ignore_index=True)
print(dfall_overall.columns)
print(dfall_overall.shape)
print(dfall_overall.isna().sum())
dfall_overall = dfall_overall.dropna(subset=['City'])

dfall_overall.head()

163488
Index(['Name', 'Age', 'M/F', 'City', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
(163488, 10)
Name                   0
Age                    0
M/F                    0
City                   1
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
dtype: int64

,Name,Age,M/F,City,Pace,Official Time,overall_result,gender_result,division_result,Year
0,"Keflezighi, Meb",38,M,San Diego,00:04:54,2:08:37,1,1,1,2014
1,"Chebet, Wilson",28,M,Marakwet,00:04:54,2:08:48,2,2,1,2014
2,"Chepkwony, Frankline",29,M,Koibatek,00:04:54,2:08:50,3,3,2,2014
3,"Shafar, Vitaliy",32,M,Lutsk,00:04:56,2:09:37,4,4,1,2014
4,"Geneti, Markos",29,M,Addis Ababa,00:04:57,2:09:50,5,5,3,2014

In [ ]:
dfall_overall.to_csv("data/dfall_overall.csv", index=False)
dfall_overall.head()

,Name,Age,M/F,City,Pace,Official Time,overall_result,gender_result,division_result,Year,Country
0,"Keflezighi, Meb",38,M,San Diego,00:04:54,2:08:37,1,1,1,2014,United States
1,"Chebet, Wilson",28,M,Marakwet,00:04:54,2:08:48,2,2,1,2014,Kenya
2,"Chepkwony, Frankline",29,M,Koibatek,00:04:54,2:08:50,3,3,2,2014,Kenya
3,"Shafar, Vitaliy",32,M,Lutsk,00:04:56,2:09:37,4,4,1,2014,Ukraine
4,"Geneti, Markos",29,M,Addis Ababa,00:04:57,2:09:50,5,5,3,2014,Ethiopia

# Find overall countries

In [ ]:
print(dfall_overall.shape)
dfall_overall['City'] = dfall_overall['City'].str.split(',').str[0].str.strip()

cities = dfall_overall['City'].unique()
print(f"Unique cities: {len(cities)}")

(163488, 10)
Unique cities: 14600

In [ ]:
"""IT DOES NOT WORK; NULL COUNTRIES. 
# !pip install geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

geolocator = Nominatim(user_agent="my_marathon_app")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

# Function to get country
def get_country(city_name):
    try:
        location = geolocator.geocode(city_name, language='en')
        if location:
            # The address usually ends with the country
            return location.address.split(',')[-1].strip()
    except:
        return None

# Get unique cities to save time
unique_cities = pd.Series(dfall_overall['City'].unique())

# WARNING: This will take hours for 15,000 cities
# Recommend testing on first 100 first:
# city_map = unique_cities.head(100).apply(get_country)

city_map = unique_cities.apply(get_country)
mapping = dict(zip(unique_cities, city_map))

dfall_overall['Country'] = dfall_overall['City'].map(mapping)
"""

In [ ]:
"""mapping_df = pd.DataFrame(list(mapping.items()), columns=['City', 'Country'])
mapping_df.to_csv("data/city_country_mapping.csv", index=False)
print(mapping_df.shape)
mapping_df.head()
"""

(14600, 2)

          City        Country
0    San Diego  United States
1     Marakwet          Kenya
2     Koibatek          Kenya
3        Lutsk        Ukraine
4  Addis Ababa       Ethiopia

In [ ]:
""" IT DOES NOT WORK
# worldcities.csv from SimpleMaps
world_cities = pd.read_csv('data/worldcities.csv') # Columns: city, country, etc.

city_map2 = world_cities.drop_duplicates('city').set_index('city')['country'].to_dict()

dfall_overall['Country2'] = dfall_overall['City'].map(city_map2)
print(dfall_overall.isna().sum())
empty_cities = dfall_overall[dfall_overall['Country2'].isna()]['City'].unique()
print(empty_cities[:20])
"""

Name                    0
Age                     1
M/F                     0
City                    0
Pace                52641
Official Time           0
overall_result          0
gender_result           0
division_result         0
Year                    0
Country            156293
Birth Year              1
ID                      1
Country2           163487
dtype: int64
<StringArray>
[      'SAN DIEGO',        'MARAKWET',        'KOIBATEK',           'LUTSK',
     'ADDIS ABABA',            'ITEN',         'MIDVALE',         'BOULDER',
         'ELDORET',       'MARRAKESH',   'MAMMOTH LAKES',          'EUGENE',
 'ROCHESTER HILLS',           'CHIBA',       'UITENHAGE',          'TUCSON',
  'LA SELVA BEACH',        'COLUMBIA',         'REDDING',          'LOWELL']
Length: 20, dtype: str

# Create Runner ID

In [ ]:
print(dfall_overall.isna().sum())

dfall_overall = dfall_overall.dropna(subset=['City'])
dfall_overall = dfall_overall.dropna(subset=['City', 'Name', 'M/F'])
dfall_overall_og = dfall_overall.copy()

for col in ['Name', 'M/F', 'City']:
    dfall_overall[col] = dfall_overall[col].astype(str).str.strip().str.upper()

dfall_overall['Year'] = pd.to_numeric(dfall_overall['Year'], errors='coerce')
dfall_overall['Age'] = pd.to_numeric(dfall_overall['Age'], errors='coerce')
dfall_overall['Birth Year'] = dfall_overall['Year'] - dfall_overall['Age']
dfall_overall['Birth Year'] = pd.to_numeric(dfall_overall['Birth Year'], errors='coerce')


identity_cols = ['Name', 'M/F', 'City', 'Birth Year']

dfall_overall['ID'] = dfall_overall.groupby(identity_cols, sort=False).ngroup()
print("=====================")
print(dfall_overall.isna().sum())

#print(dfall_overall[['ID', 'Name', 'M/F', 'City', 'Birth Year']])

Name                   0
Age                    0
M/F                    0
City                   0
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
dtype: int64
=====================
Name                   0
Age                    0
M/F                    0
City                   0
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
Birth Year             0
ID                     0
dtype: int64

# Find overall repeated names

In [86]:
df_temp = dfall_overall.groupby(['Name', 'M/F', 'City']).size().reset_index(name='Count')

def print_repeated_names(df_temp, threshold):
    more_than_threshold = df_temp[df_temp['Count'] > threshold].sort_values(['Name', 'M/F', 'City'])
    print(f"Found {more_than_threshold['Name'].nunique()} names repeated more than {threshold} times.")
    return more_than_threshold

more_than_3 = print_repeated_names(df_temp, 3)
more_than_4 = print_repeated_names(df_temp, 4)
more_than_5 = print_repeated_names(df_temp, 5)


print(dfall_overall.isna().sum())

Found 2252 names repeated more than 3 times.
Found 947 names repeated more than 4 times.
Found 388 names repeated more than 5 times.
Name                   0
Age                    0
M/F                    0
City                   0
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
Birth Year             0
ID                     0
dtype: int64

In [ ]:
dfall_overall.to_csv("data/dfall_overall.csv", index=False)

# All with countries

In [17]:
columns2 = ['Name', 'Age', 'M/F', 'City', 'Country', 'Pace', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year']

df_overall = df.copy()
df_overall.rename(columns={'Overall': 'overall_result', 'Division': 'division_result', 'Gender': 'gender_result'}, inplace=True)
print(df_overall.columns)
df_overall_country = df_overall[columns2]
print(df_overall_country.columns)
print(df_overall_country.shape)

df_overall_country = pd.concat([df_overall_country, df2014_overall,df2018_overall, df2019_overall], ignore_index=True)

#df2014_overall

#df2018_overall
#df2019_overall 
print(df_overall_country.isna().sum())

df_overall_country = df_overall_country.dropna(subset=['City'])
df_overall_country = df_overall_country.dropna(subset=['City', 'Name', 'M/F'])
df_overall_country = df_overall_country.copy()

for col in ['Name', 'M/F', 'City']:
    df_overall_country[col] = df_overall_country[col].astype(str).str.strip().str.upper()

df_overall_country['Year'] = pd.to_numeric(df_overall_country['Year'], errors='coerce')
df_overall_country['Age'] = pd.to_numeric(df_overall_country['Age'], errors='coerce')
df_overall_country['Birth Year'] = df_overall_country['Year'] - df_overall_country['Age']
df_overall_country['Birth Year'] = pd.to_numeric(df_overall_country['Birth Year'], errors='coerce')


identity_cols = ['Name', 'M/F', 'City', 'Birth Year']

# 3. Create the ID column
df_overall_country['ID'] = df_overall_country.groupby(identity_cols, sort=False).ngroup()
print("=====================")
print(df_overall_country.isna().sum())

print(df_overall_country.head())

Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'overall_result',
       'gender_result', 'division_result', 'Year'],
      dtype='str')
Index(['Name', 'Age', 'M/F', 'City', 'Country', 'Pace', 'Official Time',
       'overall_result', 'gender_result', 'division_result', 'Year'],
      dtype='str')
(79038, 11)
Name                   0
Age                    0
M/F                    0
City                   1
Country            84450
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
dtype: int64
=====================
Name                   0
Age                    0
M/F                    0
City                   0
Country            84450
Pace               52641
Official Time          0
overall_result         0
gender_result          0
division_result        0
Year                   0
Birth Year             0
ID                     0
dtype: int64
                    Name  Age M/F         City Country     Pace Official Time  \
0         DESISA, LELISA   25   M         AMBO     ETH  0:04:56       2:09:17
1  TSEGAY, YEMANE ADHANE   30   M  ADDIS ABABA     ETH  0:04:58       2:09:48
2         CHEBET, WILSON   29   M     MARAKWET     KEN  0:04:59       2:10:22
3       KIPYEGO, BERNARD   28   M      ELDORET     KEN  0:05:00       2:10:47
4          KORIR, WESLEY   32   M       KITALE     KEN  0:05:00       2:10:49

   overall_result  gender_result  division_result  Year  Birth Year  ID
0               1              1                1  2015        1990   0
1               2              2                2  2015        1985   1
2               3              3                3  2015        1986   2
3               4              4                4  2015        1987   3
4               5              5                5  2015        1983   4

In [ ]:
df_repeated_id = df_overall_country[df_overall_country.duplicated(subset=['ID'], keep=False)]
print(df_repeated_id.shape)
df_repeated_id.head()
df_repeated_id.to_csv("data/repeated_ids.csv", index=False)
#df_repeated_id_country= df_repeated_id[]

In [ ]:
df_repeated_id = pd.read_csv("data/repeated_ids.csv")
print(df_repeated_id.shape)
print(df_repeated_id.columns)
df_repeated_id.head()

(50419, 13)
Index(['Name', 'Age', 'M/F', 'City', 'Country', 'Pace', 'Official Time',
       'overall_result', 'gender_result', 'division_result', 'Year',
       'Birth Year', 'ID'],
      dtype='str')

,Name,Age,M/F,City,Country,Pace,Official Time,overall_result,gender_result,division_result,Year,Birth Year,ID
0,"DESISA, LELISA",25,M,AMBO,ETH,0:04:56,2:09:17,1,1,1,2015,1990,0
1,"TSEGAY, YEMANE ADHANE",30,M,ADDIS ABABA,ETH,0:04:58,2:09:48,2,2,2,2015,1985,1
2,"CHEBET, WILSON",29,M,MARAKWET,KEN,0:04:59,2:10:22,3,3,3,2015,1986,2
3,"KORIR, WESLEY",32,M,KITALE,KEN,0:05:00,2:10:49,5,5,5,2015,1983,4
4,"CHEPKWONY, FRANKLINE",30,M,KOIBATEK,KEN,0:05:00,2:10:52,6,6,6,2015,1985,5

In [23]:
df_repeated_id['Year'] = df_repeated_id['Year'].astype(int)

valid_years = [2015, 2016, 2017]
df_correct_countries = df_repeated_id[df_repeated_id['Year'].isin(valid_years)]
country_mapping = df_correct_countries.drop_duplicates(subset=['ID']).set_index('ID')['Country'].to_dict()
df_target_ids = df_repeated_id[df_repeated_id['ID'].isin(country_mapping.keys())].copy()
df_target_ids['Country'] = df_target_ids['ID'].map(country_mapping)
print(df_target_ids.shape)
print(df_target_ids.isna().sum())
print(df_target_ids[['ID', 'Year', 'Country']].head(10))

print(len(df_target_ids['Country'].unique()))
df_target_ids.to_csv("data/repeated_ids_with_countries.csv", index=False)

(40902, 13)
Name                  0
Age                   0
M/F                   0
City                  0
Country               0
Pace               8383
Official Time         0
overall_result        0
gender_result         0
division_result       0
Year                  0
Birth Year            0
ID                    0
dtype: int64
   ID  Year Country
0   0  2015     ETH
1   1  2015     ETH
2   2  2015     KEN
3   4  2015     KEN
4   5  2015     KEN
5   7  2015     USA
6   9  2015     UKR
7  11  2015     USA
8  12  2015     RSA
9  17  2015     USA
61

# Weather

In [22]:
import openpyxl
compass_to_deg = {
    'N': 0, 'NNE': 22.5, 'NE': 45, 'ENE': 67.5, 'E': 90, 'ESE': 112.5, 'SE': 135, 'SSE': 157.5,
    'S': 180, 'SSW': 202.5, 'SW': 225, 'WSW': 247.5, 'W': 270, 'WNW': 292.5, 'NW': 315, 'NNW': 337.5,
    'VAR': np.nan, 'CALM': np.nan # Variable or calm winds don't have a distinct direction
}

def clean_weather_data(file_path, sheet_name):
    # 1. Load the Excel file
    df_weather = pd.read_excel(file_path, sheet_name=sheet_name)
    cols_to_clean = ['Temperature', 'Dew Point','Wind Speed','Precip.']

    # 2. Extract the numbers using pandas string extraction
    for col in cols_to_clean:
        # r'(-?\d+\.?\d*)' looks for optional minus signs, digits, and optional decimals
        # [0] grabs the first match, and .astype(float) turns it into a mathematical number
        df_weather[col] = df_weather[col].str.extract(r'(-?\d+\.?\d*)')[0].astype(float)
    
    df_weather['Wind_Deg'] = df_weather['Wind'].map(compass_to_deg)
    df_weather['Wind_Deg'] = df_weather['Wind_Deg'].fillna(0)

    speed_for_calc = df_weather['Wind Speed'].where(df_weather['Wind'].isin(compass_to_deg.keys()) & (df_weather['Wind'] != 'VAR'), 0)

    # 4. Calculate the Tailwind Component using Trigonometry
    # The "ideal" tailwind comes from WSW (247.5 degrees)
    df_weather['Tailwind_Component'] = speed_for_calc * np.cos(np.radians(df_weather['Wind_Deg'] - 247.5))

    cols_to_save = ['Temperature', 'Dew Point','Precip.', 'Tailwind_Component']
    mean_weather = df_weather[cols_to_save].mean()
    return mean_weather

results = []

for year in [2014, 2015, 2016, 2017, 2018, 2019]:
    df_weather_bos = clean_weather_data("Book1.xlsx", sheet_name=f"{year}-Bos")
    df_weather_hop = clean_weather_data("Book1.xlsx", sheet_name=f"{year}-Hop")
    combined_avg = (df_weather_bos + df_weather_hop) / 2
    
    # 3. Store the result in a dictionary
    row = {
        'Year': year, 
        'Temperature': combined_avg['Temperature'], 
        'Dew Point': combined_avg['Dew Point'], 
        'Precip.': combined_avg['Precip.'], 
        'Tailwind_Component': combined_avg['Tailwind_Component']
    }
    results.append(row)

df_weather_avg = pd.DataFrame(results)
print(df_weather_avg)

df_weather_avg.to_csv("data/weather_averages.csv", index=False)
#df2014w = {'Temperature': (df2014_wb['Temperature'], df2014_wh['Temperature']), 'Humidity': (df2014_wb['Humidity'], df2014_wh['Humidity'])}

   Year  Temperature  Dew Point  Precip.  Tailwind_Component
0  2014    60.750000  34.562500  0.01250           13.106273
1  2015    42.625000  39.937500  0.02500          -13.539048
2  2016    62.875000  31.812500  0.00000           -8.500371
3  2017    67.642857  37.294643  0.00000           15.083744
4  2018    39.125000  38.500000  0.13750          -17.248595
5  2019    57.612500  51.075000  0.02125            4.678415